# Generated by Django 3.2.5 on 2021-08-08 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210808_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 8, 13, 31, 20, 939333, tzinfo=utc), null=True),
        ),
    ]
