# Generated by Django 3.2.5 on 2021-08-08 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 8, 13, 33, 6, 288790, tzinfo=utc), null=True),
        ),
    ]
